### ISSUE TITLE
Module 5 Sample Problems: Q4 & Q5 pid_t naming

### ISSUE THREAD

**Issue by tblisonb** [racuna1/ser334-public#37]
The variable names for the process IDs (pid1, pid2, pid3) should be changed to something non-numeric. It is confusing to many students that these pid_t variables aren't somehow representing the processes themselves, and this issue is made worse by naming them 1, 2, and 3 (just like how the processes are labeled).

Suggestion: maybe change them to pidA, pidB, pidC, or maybe pidX, pidY, pidZ.

**Comment by racuna1** [comment]
Seemed to be okay in Fall 2021.
